# Generated by Django 5.0.2 on 2024-03-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='api.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='remote_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
