name: Django CI

on:
  push:
    branches: [ "2024" ]
  pull_request:
    branches: [ "2024" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        python3.10 -m pip install --upgrade pip
        python3.10 -m pip install -r requirements.txt
    - name: Run Tests
      run: |
        CI=false npm i
        CI=false npm run build
        python3.10 manage.py test
